# This workflow sets up and runs MSBuild and VSTest 
# to build and test a Visual Studio solution.
name: BuildAndTest

on:
  push:
    branches: [ main ]
    
jobs:
  run-msbuild-vstest:
    runs-on: windows-latest
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
        
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        id: setup_msbuild

      - name: Run MSBuild
        id: run_msbuild
        working-directory: ./
        run: msbuild.\Lab2test.sln

      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest

      - name: Run VSTest
        id: run_vstest
        working-directory: $\Debug
        run: Lab2TestProject.exe /Platform:x32 .\Lab2TestProject.pdb
