# This workflow sets up and runs MSBuild and VSTest 
# to build and test a Visual Studio solution.
name: BuildAndTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MSVC
      uses: actions/setup-msbuild@v1
      with:
        vs-version: '16.0'
        architecture: 'x64'

    - name: Build and test
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64
        cd Debug
        Lab2TestProject.exe
