# This workflow sets up and runs MSBuild and VSTest 
# to build and test a Visual Studio solution.
name: BuildAndTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  run-msbuild-vstest:
    runs-on: windows-latest
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
        
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        id: setup_msbuild
        
      - name: Build and test
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64
          cd Debug
          Lab2TestProject.exe
